---
title: "Projects"
listing:
  contents: projects
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false

  navbar:
    left:
      - text: Part One: creating APRIORI
        href: Recipe-Association-Rules.html
      - text: Part Two: Exploring
        href: Part2flavorprofiles.html
      - text: Part Three: Creating DataFrame
        href: programsubsets.html
      - text: Python Code
---

Final Project: Recipe Data with APRIORI

I worked with a dataset from Kaggle that had recipes and all of their ingredients and I looked at it as market basket data. I changed my end product due to time constraints and knowledge, but the final product is a python code which allows users to select an ingredient from a dropdown menu and be presented with some APRIORI rules involving that ingredient. I think that although this specific case might not that be that useful, the concept and code could be applied in different useful ways. If someone wants to find a specific APRIORI rule for a specific product or object, they can just select it in a more user-friendly way and see the rule, without having to go through any data sets or codes. I plan to continue this project by making the user interface prettier and adding extra information to it. 
Part One: Creating and analyzing APRIORI rules
Part Two: Exploring Interesting (to me) APRIORI rules
Part Three: Creating a DataFrame to use in my program
Part Four: Python Program
